<?php
/**
 * @file
 * loopd_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function loopd_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Theming',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '027d3635-434d-4eb4-9e8e-7e9de610c652',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Development',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '0fd8b3d7-fa5b-4224-b95d-6e5c7488377e',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Content Structure',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '1e08a4ee-4d99-4b44-958f-dd2de90d45da',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Maps',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '2fb43a4b-bbb0-43ae-ac7a-d238ad3be7a3',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Security',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '30a8b7ce-f953-4e4e-b786-b1abc36ed038',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Workflow',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '59cc5407-950a-442c-953d-6c80a1aaa27a',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Multilingual',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '67d1d4d9-0240-48d4-a9e8-70ba7b7355d7',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Forms',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '780a608c-d24b-429c-9f50-bcf0e115d761',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Ctools',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '78e01dcd-da7e-4dbb-9d11-a38a04e60a6c',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Authoring',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '7d6f5175-3633-428d-bc4b-4f1fb4fbd95c',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Migration',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '8192ae10-860f-45f8-9daa-557d2ad84958',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Fields',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => '892aeef7-1257-4531-a55a-6d47eab7c71f',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Drupal Module',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => 'b4ff1be4-b602-48f8-83ff-d241577c2ba9',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Search',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => 'd21b77e9-5315-4798-bbf9-d1d2aba00405',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Spam',
    'description' => '',
    'format' => 'full_html_no_linebreaks',
    'weight' => 0,
    'uuid' => 'dd678623-3f45-46a9-9158-8e0c6ca79500',
    'vocabulary_machine_name' => 'tags',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
