source 'https://rubygems.org'

group :development do

  gem 'breakpoint', '~>2.0.7'
  gem 'compass', '~>0.12.2'
  gem 'sass', '~>3.2.13'
  gem 'sass-globbing', '~>1.1.1'
  gem 'zen-grids', '~>1.4'
  gem 'oily_png', '~>1.1.1'

end
